global abs32
global add32
global argc
global argv
global atoi
global atoi32
global atoibase
global atoibase32
global circle
global clrscrn
global dec32
global dispdec
global dispdec32
global disphex
global div32
global divide
global draw8x8
global drawline
global fastpres
global fastpset
global fastpxor
global fcircle
global fclose
global fgetc
global fgets
global flood
global fopen
global fopenfcb
global fopenr
global fopenrb
global fopenw
global fopenwb
global fputc
global fputs
global fread
global frect
global fseek
global ftell
global ftri
global fwrite
global getargv
global getch
global getchar
global getopt
global hexbyte
global hline
global ilprint
global inc32
global intdpix
global intsqrt
global isalnum
global isalpha
global isascii
global iscntrl
global isdigit
global isgraph
global islower
global isprint
global ispunct
global isspace
global isupper
global isxdigit
global iszero32
global itoa
global itoa32
global itoabase
global itoabase32
global kbhit
global makeargv
global mbptr
global mevents
global mfixp
global minit
global mouseoff
global mouseon
global mstat
global mul32
global multiply
global muninit
global neg32
global patblack
global patdgrey
global patlgrey
global patmgrey
global patwhite
global pfillpat
global pget
global pixstyle
global pos2addr
global preset
global pset
global putbyte
global putchar
global pxor
global qsort
global rand
global rand16
global rect
global rstr16x8
global save16x8
global sdiv32
global seed
global setfill
global sgn32
global smul32
global srand
global strcat
global strchop
global strchr
global strcmp
global strcpy
global strlen
global strncmp
global strncpy
global strprint
global strrchr
global strstr
global sub32
global swap32
global toascii
global tolower
global toupper
global vline
